name: Build CS2ServerGUI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        
    - name: Build project
      run: xmake -v -y
      
    - name: Create addons directory structure
      run: |
        mkdir -p addons/CS2ServerGUI/bin
        mkdir -p addons/metamod
        
    - name: Copy built DLL
      run: |
        copy build\windows\x64\release\CS2ServerGUI.dll addons\CS2ServerGUI\bin\
        
    - name: Create CS2ServerGUI.vdf
      run: |
        Set-Content -Path "addons\metamod\CS2ServerGUI.vdf" -Value '"Metamod Plugin"', '{', '	"alias"	"cs2servergui"', '	"file"	"addons\CS2ServerGUI\bin\CS2ServerGUI"', '}' -Encoding UTF8
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: addons
        path: addons/
        retention-days: 30 